---
- hosts: master
  vars_files:
    - vars/test_config.yaml
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - chrony
        - atop
        - htop
        - git
        - nload
        - libopenmpi-dev
        - netdata
        - automake
        - autoconf
- hosts: clients
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - chrony
        - atop
        - htop
        - git
        - nload
        - libopenmpi-dev
        - netdata
        - automake
        - autoconf
    - name: Remove strict host checking
      blockinfile:
        dest: ${HOME}/.ssh/config
        block: |
              Host *
                  StrictHostKeyChecking no
                  UserKnownHostsFile=/dev/null
        create: yes
      ignore_errors: yes
    - name: Copy ior binary
      copy:
         src:  templates/ior
         dest: /usr/local/bin
         mode: '0770'
    - name: Copy mdtest binary
      copy:
         src:  templates/mdtest
         dest: /usr/local/bin
         mode: '0770'
    - name: Symlink orted
      shell:
        cmd: ln -s /usr/lib64/openmpi/bin/orted /usr/local/bin/orted
      ignore_errors: yes
- hosts: master
  vars_files:
    - vars/test_config.yaml
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /root/ior-results
        state: directory
        mode: '0755'
    - name: Running IOR test-rf1
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-rf1"
      with_nested:
        - "{{ threads }}"
        - "{{ test_rf1 }}"
        - "{{ size }}"
    - name: Running IOR test-rf3
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-rf3"
      with_nested:
        - "{{ threads }}"
        - "{{ test_rf3 }}"
        - "{{ size }}"
    - name: Running IOR test-ec21-small
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec21-small"
      with_nested:
        - "{{ threads }}"
        - "{{ test_ec21_small }}"
        - "{{ size }}"
    - name: Running IOR test-ec21
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec21"
      with_nested:
        - "{{ threads }}"
        - "{{ test_ec21 }}"
        - "{{ size }}"
    - name: Running IOR test-ec42-small
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec42-small"
      with_nested:
        - "{{ threads }}"
        - "{{ test_ec42_small }}"
        - "{{ size }}"
    - name: Running IOR test-ec42
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec42"
      with_nested:
        - "{{ threads }"
        - "{{ test_ec42 }}"
        - "{{ size }}"
    - name: Running IOR test-ec82-small
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec82-small"
      with_nested:
        - "{{ threads }}"
        - "{{ test_ec82_small }}"
        - "{{ size }}"
    - name: Running IOR test-ec82
      shell:
        cmd: "{{ mpi }} -wd {{ mountpoint }} {{ nodes}} {{ item.0 }} {{ ior }} {{ item.1 }} {{item.2 }} | tee >> {{ results }}/test-ec82"
      with_nested:
        - "{{ threads }}"
        - "{{ test_ec82 }}"
        - "{{ size }}"
