registry_ip: 172.16.78.211
registry: mpich.quobyte.local
results: ~/ior-results
mpi: /quobyte/config/mpich-install/bin/mpirun
ior_posix: "/quobyte/config/ior/bin/ior -vvv -a POSIX -i3 -g -r -w -T 5 -F -C -k -b 10g"
ior_mpiio: "/quobyte/config/ior/bin/ior -vvv -a MPIIO -i3 -g -r -w -T 5 -F -C -k -b 10g"
mdtest: "/quobyte/config/ior/bin/mdtest -z 0 -b 0 -I 100000 -w 1000000 -i 3"
nodes: "-machinefile nodelist"

mountpoint_mpiio: "-o quobyte://mpich.quobyte.local"
mountpoint_posix: "-o /quobyte"

threads:
  - "-np 4"
  - "-np 24"
  - "-np 48"
  - "-np 72"
# increase open processes for user /etc/security/limit.conf?
size:
  - "-t 1m"
  - "-t 4k"
test_rf1: 
  - "/vol0-rf1/seq"
  - "/vol0-rf1/rand -z"
test_rf3:
  - "/vol0-rf3/seq"
  - "/vol0-rf3/rand -z"
test_ec42:
  - "/vol0-ec42/seq"
test_ec82:
  - "/vol0-ec82/seq"
test_mdtest:
  - "-d /quobyte/vol0-rf1/mdtest"
  - "-d /quobyte/vol0-rf3/mdtest"

